UnitTypes.gamma.weapons.add(UnitTypes.corvus.weapons.get(0))
UnitTypes.gamma.weapons.add(UnitTypes.toxopid.weapons.get(2))
UnitTypes.gamma.weapons.add(UnitTypes.vela.weapons.get(0))
UnitTypes.gamma.weapons.add(UnitTypes.poly.weapons.get(0))
UnitTypes.gamma.weapons.add(UnitTypes.quad.weapons.get(0))
